# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-22 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qrcode',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
