# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-14 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='price',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
