# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-15 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_auto_20180314_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicedetail',
            old_name='price',
            new_name='cost_price',
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='selling_price',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
