# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-15 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0005_auto_20180315_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_size',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
