# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-16 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0006_invoice_discount_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cost_total',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
