# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-16 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0007_invoice_cost_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='cost_total',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
