# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-17 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0008_auto_20180316_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='discount.Discount'),
        ),
    ]
