# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-20 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discount_type', models.CharField(choices=[('percent', 'Percent'), ('cash', 'Cash')], max_length=10)),
                ('discount_value', models.FloatField()),
            ],
        ),
    ]
