# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-18 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potongan', models.FloatField(default=5000)),
            ],
        ),
    ]
