# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-18 11:32
from __future__ import unicode_literals

from django.db import migrations


def create_config(apps, schema_editor):
    Config = apps.get_model('config', 'Config')
    Config.objects.create(potongan=5000)

class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_config),
    ]
