# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-19 12:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashier', '0010_auto_20180317_2010'),
        ('product', '0002_auto_20171124_0212'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Retur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('qty', models.IntegerField()),
                ('potongan', models.FloatField(blank=True, default=None)),
                ('total', models.FloatField(blank=True, default=None)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retur_by', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retur', to='cashier.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='ReturDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('subtotal', models.FloatField(blank=True, default=None)),
                ('product_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductWarehouse')),
                ('retur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='customer_return.Retur')),
            ],
        ),
    ]
