# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-21 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_return', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retur',
            old_name='actor',
            new_name='cashier',
        ),
        migrations.AddField(
            model_name='returdetail',
            name='selling_price',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
